name: Tokens
version: 1.0.0
main: uk.thecodingbadgers.tokens.Tokens
authors: [n3wton, TheFish97]
description: Token collection and using plugin
depend: [Citizens]

commands:
    tokens:
        description: Tokens Command
        usage: /tokens <command> <args>
        aliases: [tk]

